name: Keep Streamlit Apps Awake

on:
  schedule:
    # This runs every 8 hours (at 00:00, 08:00, and 16:00 UTC)
    - cron: '0 */8 * * *'
  workflow_dispatch: # This allows you to run it manually for testing

jobs:
  ping_apps:
    runs-on: ubuntu-latest
    steps:
      - name: Ping FASTA Utility
        run: curl -I https://frankneuro-fasta.streamlit.app/

      - name: Ping Primer Utility
        run: curl -I https://frankneuro-primer.streamlit.app/
